//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace E3Collector
{
    [Serializable]
    internal class ApiException : Exception
    {
        private string v;
        private int status_;
        private string text;
        private Dictionary<string, IEnumerable<string>> headers_;
        private object value;

        public ApiException()
        {
        }

        public ApiException(string message) : base(message)
        {
        }

        public ApiException(string message, Exception innerException) : base(message, innerException)
        {
        }

        public ApiException(string v, int status_, string text, Dictionary<string, IEnumerable<string>> headers_, object value)
        {
            this.v = v;
            this.status_ = status_;
            this.text = text;
            this.headers_ = headers_;
            this.value = value;
        }

        protected ApiException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }

    [Serializable]
    internal class ApiException<T> : Exception
    {
        private string v;
        private int status_;
        private string text;
        private Dictionary<string, IEnumerable<string>> headers_;
        private Error @object;
        private object value;

        public ApiException()
        {
        }

        public ApiException(string message) : base(message)
        {
        }

        public ApiException(string message, Exception innerException) : base(message, innerException)
        {
        }

        public ApiException(string v, int status_, string text, Dictionary<string, IEnumerable<string>> headers_, Error @object, object value)
        {
            this.v = v;
            this.status_ = status_;
            this.text = text;
            this.headers_ = headers_;
            this.@object = @object;
            this.value = value;
        }

        protected ApiException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}